system:
  db-mode: "postgres"
  jwt:
    key: "Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5" # 用于签发和解析 Token 的密钥
    expiration: 1000h                                     # 签发 Token 的过期时间

mysql:
  addr: "127.0.0.1:3306"        # 数据库地址（含端口）
  username: "root"              # 用户名
  password: "root"              # 密码
  database: "root"              # 数据库名
  max-idle-conns: 10            # 最大空闲连接数
  max-open-conns: 50            # 最大打开连接数
  max-conns-life-time: 3600     # 连接最大存活时间（秒）

postgres:
  addr: "127.0.0.1"
  port: "5432"
  username: "jing"
  password: ""
  database: "fastgo"
  ssl-mode: "prefer"
  max-idle-conns: 10            # 最大空闲连接数
  max-open-conns: 50            # 最大打开连接数
  max-conns-life-time: 3600     # 连接最大存活时间（秒）

log:
  format: text
  level: info
  output: stdout